# Generated by Django 3.1.3 on 2020-12-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhD_Admission', '0003_auto_20201112_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['Application_ID']},
        ),
    ]
