# Generated by Django 3.1.3 on 2020-12-01 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhD_Admission', '0004_auto_20201201_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['App_Seq_No']},
        ),
    ]
