# Generated by Django 3.1.3 on 2020-12-01 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhD_Admission', '0005_auto_20201201_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('faculty_decision', models.CharField(max_length=50)),
                ('assistantship_decision', models.CharField(max_length=50)),
                ('nomination', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=50000)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhD_Admission.applicant')),
            ],
        ),
    ]
